name: Release Docker Image

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata
        run: |
          TAG=$(git tag --points-at HEAD | head -n1)
          if [ -n "$TAG" ]; then
            echo "tag=$TAG" >> $GITHUB_ENV
            echo "tagged=true" >> $GITHUB_ENV
          else
            echo "tag=latest" >> $GITHUB_ENV
            echo "tagged=false" >> $GITHUB_ENV
          fi

          SHORT_SHA=$(git rev-parse --short HEAD)
          echo "sha=${SHORT_SHA}" >> $GITHUB_ENV

      - name: Build and push primary tag
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: firefox2100/dedi-gateway:${{ env.tag }}
          labels: |
            org.opencontainers.image.revision=${{ env.sha }}
            org.opencontainers.image.version=${{ env.tag }}
            org.opencontainers.image.ref.name=${{ env.tag }}

      - name: Build and push latest tag
        if: ${{ env.tagged == 'true' }}
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: firefox2100/dedi-gateway:latest
          labels: |
            org.opencontainers.image.revision=${{ env.sha }}
            org.opencontainers.image.version=${{ env.tag }}
            org.opencontainers.image.ref.name=latest
